version: '3.8'
services:
  frontend:
    build: ./front-rep-arquivos
    ports:
      - "5173:80" 
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    ports:
      - "9092:8082" 